---
- name: test playbook
  hosts: "{{ hostvars['localhost']['host_group'] }}"
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - ansible_ssh_private_key_file: .vagrant/machines/default/virtualbox/private_key

  roles:
  tasks:
