---
- name: test playbook
  hosts: "scalefactory-vbox"
  gather_facts: no
  become: true
  become_user: root
  become_method: sudo
  vars:
    - ansible_ssh_private_key_file: .vagrant/machines/default/virtualbox/private_key
    - ansible_os_family: RedHat
    - ansible_distribution: CentOS
    - ansible_distribution_major_version: 6

  roles:
   - role: nginxinc.nginx-oss

  tasks:

    - name: start nginx
      shell: sudo service nginx start

    - name: install development tools
      shell: yum groupinstall -y 'development tools'

    - name: install development software
      yum: pkg={{item}} state=installed
      with_items:
       - python-devel.x86_64
       - zlib-devel
       - openssl-devel
       - sqlite-devel
       - bzip2-devel

    - name: get python setup.py
      shell: wget --no-check-certificate https://pypi.python.org/packages/source/s/setuptools/setuptools-1.4.2.tar.gz

    - name: Extract the files from the archive
      shell: tar -xvf setuptools-1.4.2.tar.gz

    - name: Enter the extracted directory
      shell: cd setuptools-1.4.2 && sudo python setup.py install

    - name: get pip
      shell: curl https://bootstrap.pypa.io/2.6/get-pip.py -o get-pip.py

    - name: install pip
      shell: sudo python get-pip.py

    - name: copy fizzbuzz into vagrant machine
      copy:
       src: fizzbuzz.py
       dest: /home/vagrant/fizzbuzz.py
       owner: root
       group: root
       mode: 0777

    - name: install uwsgi
      shell: sudo pip install uwsgi

    - name: copy in the webapp
      copy:
       src: webapp/
       dest: /home/vagrant/webapp
       owner: root
       group: root
       mode: 0777
